# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timelineevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='id',
        ),
        migrations.AddField(
            model_name='timeline',
            name='eid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='eid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
